sudo: required

services:
    - docker
        
env:
  jobs:
    - IMAGE=hippylib/fenics:latest
    - IMAGE=quay.io/fenicsproject/stable:2019.1.0.r3
    - IMAGE=ceciledc/fenics_mixed_dimensional

jobs:
    include:
    - stage: Unit tests
      script: ./ci/run_unittest.sh
    - stage: Applications
      script: ./ci/run_applications.sh
    - stage: Notebooks
      script: ./ci/run_notebooks.sh
